### ISSUE TITLE
Uninstall hin for Sonoma Blocker is wrong

### ISSUE THREAD

**Issue by kadolino** [Theile/sonomablocker#1]
Uninstall hint must be customized for sonoma blocker. This is wrong:

----

To fully uninstall bigsurblocker, run the following (as root or with sudo):

```
current_user_uid=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/UID :/ && ! /loginwindow/ { print $3 }' )

launchd_item_path="/Library/LaunchAgents/com.hjuutilainen.bigsurblocker.plist"
launchctl bootout gui/${current_user_uid} "${launchd_item_path}"

rm -f /Library/LaunchAgents/com.hjuutilainen.bigsurblocker.plist
rm -f /usr/local/bin/bigsurblocker

pkgutil --forget com.hjuutilainen.bigsurblocker
```

**Comment by Theile** [comment]
I think you might have skipped this line, before scrolling to the bottom:
“The rest of this README is from that original project:”

The uninstaller script is placed in the repo.
